### ISSUE TITLE
No module named 'pytest'

### ISSUE THREAD

**Issue by Tilix4** [douglaskastle/blender-fake-addon#2]
Hi, I followed the readme until I get this error:
```
C:\Users\me\Downloads\blender-fake-addon-master>py scripts/run_blender.py 2.80-windows64
C:\Users\me\Downloads\blender-2.80-windows64\blender -b --python "scripts/load_pytest.py"
Read prefs: C:\Users\me\AppData\Roaming\Blender Foundation\Blender\2.80\config\userpref.blend
found bundled python: C:\Users\me\Downloads\blender-2.80-windows64\2.80\python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\me\Downloads\blender-fake-addon-master\scripts/load_pytest.py", line 2, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
Saved session recovery to 'C:\Users\me\AppData\Local\Temp\quit.blend'

Blender quit
```

But if I go into the same Blender, and type in the console: `import pytest` it works and I have no error. 
**pytest** is also installed in my python.

**Comment by Tilix4** [comment]
It was looking to the wrong Blender file. The script looks by default into the parent directory of the repository.

**Comment by douglaskastle** [comment]
sorry i missed this issue, I was on vacation and off the internet.  I am happy to see you resolved your issue and you are also making use of the plugin.
